# https://github.com/tadaspetra/todoapp/blob/master/todo_app/analysis_options.yaml
# https://www.youtube.com/watch?v=aiTTClKJbnw&t=403s&ab_channel=freeCodeCamp.org

# https://pub.dev/packages/lint

include: package:lint/analysis_options.yaml
